Add  braching workflows

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,10 +1,11 @@
-name: Final CI/CD
+name: CI/CD
 
 env:
+  DEPLOY_TYPE = 'qjvm' #knative qjvm qnative
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
   OPENSHIFT_NAMESPACE: "rr42724-dev"
-  APP_NAME: "punctual-phoenix-kn-native"
+  APP_NAME: "punctual-phoenix"
   APP_PORT: ""
   IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
   IMAGE_REGISTRY_USER: ${{ github.actor }}
@@ -44,10 +45,20 @@ jobs:
       run: |
         ls -lrt
         echo "✅ Checkout Successful"
+
     - name: Build
+      if: env.DEPLOY_TYPE == 'knative' || env.DEPLOY_TYPE == 'qnative'
       run: |
         ./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
         echo "✅ Native Image build Successful"
+    - name: Build
+      if: env.DEPLOY_TYPE == 'qjvm'
+      run: |
+        ./gradlew clean build
+        echo "✅ JVM Image build Successful"
+        
+    
+
     - name: Get Version Number
       id: get-ver
       run: echo "::set-output name=app-ver::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
@@ -57,13 +68,26 @@ jobs:
         echo "IMAGE_TAGS=latest ${{ steps.get-ver.outputs.app-ver }} ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
 
     - name: Build from Dockerfile
+      if: env.DEPLOY_TYPE == 'qjvm'
       id: build-image
       uses: redhat-actions/buildah-build@v2
       with:
-        image: ${{ env.APP_NAME }}
+        image: ${{ env.APP_NAME }}-${{ env.DEPLOY_TYPE }}
+        tags: ${{ env.IMAGE_TAGS }}
+        dockerfiles: |
+          ./src/main/docker/Dockerfile.jvm
+    - name: Build from Dockerfile
+      if: env.DEPLOY_TYPE == 'knative' || env.DEPLOY_TYPE == 'qnative'
+      id: build-image
+      uses: redhat-actions/buildah-build@v2
+      with:
+        image: ${{ env.APP_NAME }}-${{ env.DEPLOY_TYPE }}
         tags: ${{ env.IMAGE_TAGS }}
         dockerfiles: |
           ./src/main/docker/Dockerfile.native
+          
+          
+
     - name: Push to registry
       id: push-image
       uses: redhat-actions/push-to-registry@v2
@@ -73,7 +97,9 @@ jobs:
         registry: ${{ env.IMAGE_REGISTRY }}
         username: ${{ env.IMAGE_REGISTRY_USER }}
         password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
+
     - name: Upload kNative YML
+      if: env.DEPLOY_TYPE == 'knative'
       uses: actions/upload-artifact@v3
       with:
         name: ${{ env.APP_NAME }}-${{ steps.get-ver.outputs.app-ver }}
@@ -86,8 +112,9 @@ jobs:
         echo "📌 Image ${{ steps.push-image.outputs.registry-path }}"
         echo "📌 NS ${{env.OPENSHIFT_NAMESPACE}}"
 
-  deploy-k-native:
+  deploy-knative:
       name: Deploy K Native on Openshift.
+      if: env.DEPLOY_TYPE == 'knative'
       needs: test-and-package
       runs-on: ubuntu-latest
       steps:
@@ -128,3 +155,53 @@ jobs:
         run: |
           echo "📌 APP NAME ${APP_NAME}"
           echo "📌 NS ${{env.OPENSHIFT_NAMESPACE}}"
+
+  deploy-ose:
+    name: Deploy on Openshift.
+    if: env.DEPLOY_TYPE == 'qjvm' || env.DEPLOY_TYPE == 'qnative'
+    needs: test-and-package
+    runs-on: ubuntu-latest
+    steps:
+      - name: Switch Namespace
+        if: github.ref == 'refs/heads/main'
+        run: |
+          echo "OPENSHIFT_NAMESPACE=rr42724-stage" | tee -a $GITHUB_ENV
+      - name: Install oc
+        uses: redhat-actions/openshift-tools-installer@v1
+        with:
+          oc: 4
+
+      - name: Log in to OpenShift
+        uses: redhat-actions/oc-login@v1
+        with:
+          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+
+      - name: switch projects
+        run: |
+          oc project ${{ env.OPENSHIFT_NAMESPACE }}
+
+      - name: Create and expose app
+        id: deploy-and-expose
+        uses: redhat-actions/oc-new-app@v1
+        with:
+          app_name: ${{ env.APP_NAME }}-${{ env.DEPLOY_TYPE }}
+          image: ${{ steps.push-image.outputs.registry-path }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+          port: ${{ env.APP_PORT }}
+
+      - name: Print application URL
+        env:
+          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+                
